story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story4.urls')),
    path('', include('story1.urls')),
    path('',include('story5.urls')),
    path('',include('story6.urls')),
    path('',include('story7.urls')),
    path('',include('story8.urls')),
     path('',include('story9.urls'))
]

story6/urls.py
from django.urls import path
from . import views


app_name = 'story6'

urlpatterns = [
    path('story6/',views.createKegiatan,name = 'homepage'),
    path('createKegiatan', views.createKegiatan, name='createKegiatan'),
    path('createPeserta/<int:kegiatan_id>/', views.createPeserta, name='createPeserta'),
    
    
]

story6/models.py
from django.db import models
# Create your models here.
from django.forms import ModelForm

class modelKegiatan(models.Model):
    namaKegiatan = models.CharField(max_length=100)
    
    def __str__(self):
		    return "{}".format(self.namaKegiatan)

class modelPeserta(models.Model) :
    namaPeserta = models.CharField(max_length=100)
    kegiatan = models.ForeignKey(modelKegiatan, on_delete= models.CASCADE)
    
    def __str__(self):
		    return "{}".format(self.namaPeserta)

# Create your models here.

	

story6/forms.py
from .models import modelKegiatan, modelPeserta
from django import forms


class formPeserta(forms.ModelForm):
    class Meta:

        model = modelPeserta
        fields = ('namaPeserta',)


class formKegiatan(forms.ModelForm):
    class Meta:

        model = modelKegiatan
        fields = ('namaKegiatan',)

story6/views.py
from django.shortcuts import render
from .models import modelKegiatan, modelPeserta
from .forms import formKegiatan, formPeserta

# Create your views here.

def createKegiatan(request):
    listKegiatan = modelKegiatan.objects.all()
    kegiatan = formKegiatan(request.POST or None)
    peserta = formPeserta(request.POST or None)
    context = {
            'list_kegiatan' : listKegiatan,
            'kegiatan': kegiatan, 'peserta':peserta
    }
    if request.method == 'POST' :
        if kegiatan.is_valid() :
            listKegiatan.create(
                namaKegiatan = kegiatan.cleaned_data.get('namaKegiatan'),
            )
    return render(request,'page.html',context)
    
def createPeserta(request, kegiatan_id):
    listPeserta = modelPeserta.objects.all()
    listKegiatan = modelKegiatan.objects.get(id=kegiatan_id)
    peserta = formPeserta(request.POST or None)
    context = {
        'listKegiatan':listKegiatan,
        'peserta': peserta,
        'list_peserta' : listPeserta
    }
    if request.method == 'POST' :
        if peserta.is_valid() :
            listPeserta.create(
                namaPeserta = peserta.cleaned_data.get('namaPeserta'),
                kegiatan = listKegiatan
            )
    return render (request,"buatPeserta.html",context)

story6/templates/base3.html
{%load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>
            {% block page_title %}  

            {% endblock page_title %}
        </title>
          <link rel="stylesheet" href="{% static 'bootstrap.css' %}">
          <link rel="stylesheet" href="{% static 'style.css' %}">   
    </head>
    <body>
        <body style="background-color:  #EFECEB; position : sticky;" >
            <ul class="nav nav-pills">
            <li class="nav-item">
            <a class="nav-link active" href="#" >Story 6</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{%url 'story6:createKegiatan'%}">Kegiatan</a>
            </li>
            </ul>
            </body>
            <div style="background-color: #FFA300;padding-left: 2em;padding-right: 2em;">
        {%block content  %}
        {% endblock content %}
        </div>
    </body>
</html> 

story6/templates/buatPeserta.html
{% extends 'base3.html' %}
{%load static %}

{% block page_title %}  
{{page_title}}
{% endblock page_title %}
    
{% block content %}


<h3>
    {{page_title}}
</h3>    

        <form method="POST">
        
            {% csrf_token %}
            <table>
                {{peserta.as_table}}
            </table>
            <button type="Submit">Tambah </button>
        </form>
      <b> List Peserta</b>
         <table class="table-hover  ">
            {% for i in list_peserta %}
                <tr> 
                    {% if i.kegiatan == listKegiatan %}
                    <td>
                    {{i.namaPeserta}}
                    </td>
                    {% endif %}
                </tr>          
            {% endfor %}
        </table>
        


{% endblock content %}

story6/templates/page.html
{% extends "base3.html" %}
{%load static %}

{% block page_title %}
	{{page_title}}
{% endblock page_title %}

{% block content %}
Test disini
    <h2>{{page_title}}</h2>
      <form method="POST" >
    {%csrf_token%}
    <table>
        {{kegiatan.as_table}}
    </table>
    <button class="btn btn-light">Tambah</button>
    </form>

<br/>
    Halo Semua
    <h4><b>List kegiatan</b></h4>
    <table class="table-hover  border">
        {% for i in list_kegiatan %}
            <tr> 
                <td style="padding: 2em">
                <h5>{{i.namaKegiatan}}</h5>
                </td>
                <td style="padding-bottom: 2em ;">
                    <a class=" btn btn-light" href = "{% url 'story6:createPeserta' kegiatan_id=i.id%}"> Add/edit </a>
                </td>
            </tr>          
        {% endfor %}
    </table>
  
{% endblock content %}