story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story4.urls')),
    path('', include('story1.urls')),
    path('',include('story5.urls')),
    path('',include('story6.urls')),
    path('',include('story7.urls')),
    path('',include('story8.urls')),
     path('',include('story9.urls'))
]

story5/urls.py
from django.urls import path
from . import views


app_name = 'story5'

urlpatterns = [
    path('story5/' ,views.createMatkul, name='createMatkul'),
    path('createMatkul/' ,views.createMatkul, name='createMatkul'),
    path('lihatMatkul/' ,views.lihatMatkul, name='lihatMatkul'),
    path('detail/<str:cek_id>/' ,views.detail, name='detail'),
    path('delete/<int:delete_id>/', views.deleteMatkul, name='delete'),
    
    
]

story5/models.py
from django.db import models
# Create your models here.
from django.forms import ModelForm


# Create your models here.
class mkModel(models.Model) :
	LIST_MATKUL = [
		('Dasar-Dasar Pemrograman','Dasar-Dasar Pemrograman'),
		('Struktur Data dan Algoritma','Struktur Data dan Algoritma'),
		('Pengantar Organisasi Komputer','Pengantar Organisasi Komputer'),
		('Perancangan dan Pemrograman Web','Perancangan dan Pemrograman Web'),
		('Matematika Dasar','Matematika Dasar'),
		('Matematika Diskret','Matematika Diskret')
	]
	LIST_DOSEN = [
		('Gilang,S.Kom.,M.Kom.','Gilang,S.Kom.,M.Kom.'),
		('Dr.Yudishtira M.CompSc.','Dr.Yudishtira M.CompSc.'),
		('Catur, S.Kom.,M.Kom.','Catur, S.Kom.,M.Kom.'),
		('Cey,M.CompSc','Cey,M.CompSc'),
		('Prof.Geceye,M.CompSc.','Prof.Geceye,M.CompSc.'),
		('Ir.Lang.M.Si.','Ir.Lang.M.Si.')
	]
	LIST_JAM =[
		('Senin 08.00-10.00','Senin 08.00-10.00'),
		('Senin 10.00-12.00','Senin 10.00-12.00'),
		('Selasa 08.00-10.00','Selasa 08.00-10.00'),
		('Selasa 10.00-12.00','Selasa 10.00-12.00'),
	]
	LIST_Ruangan =[
		('2.301','2.301'),
		('2.302','2.302'),
		('2.303','2.303'),
		('2.304','2.304'),
		('2.401','2.401'),
		('2.402','2.402'),
		('2.403','2.403'),
		('2.404','2.404')
	]

	nama = models.CharField(
					max_length=100 , 
					choices = LIST_MATKUL, 
					default='Dasar-Dasar Pemrograman')
	Dosen =  models.CharField(
					max_length=100 , 
					choices = LIST_DOSEN, 
					default='Gilang,S.Kom.,M.Kom.')
	jam =  models.CharField(
					max_length=100 , 
					choices = LIST_JAM, 
					default='Selasa 10.00-12.00')
	ruangan = models.CharField(
		max_length=100, choices = LIST_Ruangan, default='2.304'
	)
		
	
	def __str__(self):
			return "{}".format(self.nama)




# Create your models here.

story5/forms.py
'''from django import forms
from .models import mkModel'''


from django import forms
from .models import mkModel

class mkForm(forms.ModelForm):
    class Meta : 
        model = mkModel
        fields = [
            'nama','ruangan','Dosen','jam'
		]

story5/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .models import mkModel
from .forms import mkForm

# Create your views here

def lihatMatkul(request):
    matkul = mkModel.objects.all()

    context = {'page_title':'List Mata Kuliah',
    'matkul':matkul
    }   

    return render(request,'lihatMatkul.html',context)

def detail(request,cek_id):
    context ={'page_title':'Detail Mata Kuliah',
     'cek':cek_id}

    return render(request,'detail.html',context)

def createMatkul(request):
    mataKuliah_form = mkForm(request.POST or None)
    if request.method == 'POST':
        if mataKuliah_form.is_valid():
            mataKuliah_form.save()
            status ={"status":"Data Berhasil ditambahkan","stat":"2"}
            return render(request,'pageMatkul.html',status)

    context ={
            'page_title':'Tambah Matkul',
            'matkul_form': mataKuliah_form,'stat':'1'
    }
    return render(request,'pageMatkul.html',context)

def deleteMatkul(request,delete_id):
    mkModel.objects.filter(id=delete_id).delete()
    return redirect ('story5:lihatMatkul')

story5/templates/detail.html
{% extends "base2.html" %}


{% block page_title %}
	{{page_title}}
{% endblock page_title %}

{% block content %}
    <h2>{{page_title}}</h2>
  {%if cek == 'Dasar-Dasar Pemrograman' %}
    <div class="col-5 text-justify">
        <div class=" row">
        <b>Dasar-Dasar Pemrograman</b>
        </div>
        <div class='row'>
            Jumlah SKS : 4 <br/>Prasyarat : Tidak Ada<br/><br/>
        </div>
        <div class='row'>
            Mata kuliah yang mempelajari tentang dasar-dasar pemrogramman, menggunakan bahasa python sebagai media pembelajaran. Setelah pembelajaran mahasiswa diharapkan dapat mengerti syntax di python, serta penggunaan method dan class di Python
        </div>
    </div>
    {%endif%}
    {%if cek == 'Struktur Data dan Algoritma' %}
    <div class="col-5  text-justify">
        <div class=" row">
            <b>Struktur Data dan Algoritma</b> 
        </div>
        <div class='row'>
            Jumlah SKS : 4 <br/> Prasyarat : Dasar-Dasar Pemrograman 2 <br/><br/>
        </div>
        <div class="row">
        Mata kuliah yang mempelajari tentang analisa Algoritma dan Struktur Data, mata kuliah ini memiliki tingkat kesulitan yang tinggi, namun akan mengasah kemampuan programming yang dimiliki mahasiswa
        </div>
    </div>
    {%endif%}
    {%if cek == 'Pengantar Organisasi Komputer' %}
    <div class="col-5  text-justify">
        <div class=" row">
           <b> Pengantar Organisasi Komputer</b>
        </div>
        <div class='row'>
            Jumlah SKS : 3 <br/> Prasyarat : Pengantar Sistem Digital <br/><br/>
        </div>
        <div class="row">
            Mata kuliah yang mempelajari tentang organisasi komputer, serta juga mempelajari penggunaan bahasa assembly serta proses pengubahan bahasa assembly ke bahasa mesin, 
        </div>
    </div>
    {%endif%}
    {%if cek == 'Matematika Diskret' %}
    <div class="col-5  text-justify">
        <div class=" row">
           <b> Matematika Diskret</b>
        </div>
        <div class='row'>
            Jumlah SKS : 3 <br/> Prasyarat : Tidak ada <br/><br/>
        </div>
        <div class="row">
            Mata kuliah yang mempelajari tentang logika matematika, induksi matematika, kombinatorika, serta himpunan dan relasi
        </div>
    </div>
    {%endif%}
    
    {%if cek == 'Matematika Dasar' %}
    <div class="col-5  text-justify">
        <div class=" row">
            <b>Matematika Dasar</b>
        </div>
        <div class='row'>
            Jumlah SKS : 3 <br/> Prasyarat : Tidak ada <br/><br/>
        </div>
        <div class=" row">
            Mata kuliah yang mempelajari tentang kalkulus, yaitu tentang teorema limit, turunan, integral, barisan tak hingga dll.
        </div>
    </div>
    {%endif%}
    <a class="btn btn-dark" href="{%url 'story5:lihatMatkul'%}">Kembali</a>

    
{% endblock content %}

story5/templates/lihatMatkul.html
{% extends "base2.html" %}
{%load static %}

{% block page_title %}
	{{page_title}}
{% endblock page_title %}

{% block content %}
    <h2>{{page_title}}</h2>
    <table class="table-hover table border border-dark ">
        <thead>
            <tr>
                <th scope="col">
                    Nama Mata Kuliah
                </th>
                <th scope="col">
                    Ruangan
                </th>
                <th scope="col">
                    Nama Dosen
                </th>
                <th scope="col">
                    Waktu
                </th>
                <th scope="col">
                    Action
                </th>
            </tr>
        </thead>
            {% for i in matkul %}
            <tr>
                <td>
                    <a class="btn" href="{%url 'story5:detail' cek_id=i.nama %}">{{i.nama}}</a>
                </td>
                <td>
                    {{i.ruangan}}
                </td>
                <td>
                    {{i.Dosen}}
                </td>
                <td>
                    {{i.jam}}
                </td>
                <td>
                    <a href="{%url 'story5:delete' delete_id=i.id %}" class="btn btn-danger">x</a>
                </td>                
            </tr>
            {% endfor %}
    </table>
    <a class="btn btn-dark" href="{%url 'story5:createMatkul'%}">Tambah</a>
    
{% endblock content %}

story5/templates/pageMatkul.html
{% extends 'base2.html' %}
{%load static %}

{% block page_title %}  
{{page_title}}
{% endblock page_title %}
    
{% block content %}

<center class="border-2">
<h3>
    {{page_title}}{{status}}
</h3>    

    {%if stat == "1" %}
        <form method="POST" action="{%url 'story5:createMatkul'%}">
        
            {% csrf_token %}
            <table>
                {{matkul_form.as_table}}
            </table>
            <button type="Submit">Tambah </button>
           
        </form>
    {%elif stat == "2" %}
        <a class="btn btn-dark" href="">OK</a>
    {%endif %}
</center> 

{% endblock content %}