story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story4.urls')),
    path('', include('story1.urls')),
    path('',include('story5.urls')),
    path('',include('story6.urls')),
    path('',include('story7.urls')),
    path('',include('story8.urls')),
     path('',include('story9.urls'))
]

story4/urls.py
from django.urls import path
from . import views
#from story5 import urls
#from story1 import urls
from story6 import urls


app_name = 'story4'

urlpatterns = [
    path('story4', views.index, name='story4'),
    path('experience/', views.experience, name='experience'),
    path('achievement/', views.achievement, name='achievement'),
    path('volun/', views.volun, name='volun'),
    path('skills/', views.skills, name='skills'),
    path('about/', views.about, name='about'),
     path('edu/', views.edu, name='edu'),
     #path('story5',urls.views.lihatMatkul, name='story5'),
     #path('story1',urls.views.story1 , name="story1"),
     #path('story5',urls.views.pageMatkul, name="story5")
]

story4/models.py
from django.db import models
#create your model here

story4/forms.py
'create your form here'

story4/views.py
from django.shortcuts import render, redirect



# Create your views here.
def index(request):
    return render(request, 'index.html')

def experience(request):
    return render(request, "experience.html")

def achievement(request):
    return render(request, "achievement.html")

def skills(request):
    return render(request, "skills.html")

def volun(request):
    return render(request, "volun.html")

def about(request):
    return render(request, "about.html")

def edu(request):
    return render(request, "edu.html")

story4/templates/about.html
{% extends 'base.html' %}
{% load static %}
<html>
    <head>
        <title>About</title>
        {% block head %}
        <link rel="stylesheet" href="{%static 'css/bootstrap-grid' %}" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link href="{%static 'style.css' %}" rel="stylesheet" type="text/css" />
        {% endblock %}
    </head>
    {%block content %}
    <body>
        
        <div class="row page ">
            <div>
                <a href="{% url 'story4:index' %}">
                <img class="buttonimg big" src="{%static 'button.png' %}">
                </a>
            </div>
            <div class="textbox pages" >
                <div class="subtitle bigger">
                    About me
                </div>
                <div class="content pad">
                    <div class="sub bigger" style="text-align: justify;"> I’m  a Computer Science Student and like anything about social service. I have confidence in public speaking. I like working in teams and learning new things</div>
                </div>
               
            </div>
        </div>
        
    </body>
    {% endblock %}
</html>

story4/templates/achievement.html
{% extends 'base.html' %}
{% load static %}
<html>
    <head>
        <title>Achievement</title>
        {% block head %}
        <link rel="stylesheet" href="{%static 'css/bootstrap-grid' %}" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link href="{%static 'style.css' %}" rel="stylesheet" type="text/css" />
        {% endblock %}
    </head>
    {%block content %}
    <body style="background: #FFA300;;">
        <div class="row page ">
            <div>
                <a href="{% url 'story4:index' %}">
                <img class="buttonimg big" src="{%static 'button.png' %}">
                </a>
            </div>
            <div class="textbox pages" >
                <div class="subtitle bigger">
                    Achievement
                </div>
                <div class="volun">
                <div class="content pads">
                    <div class="sub bigger">Awardee Beasiswa Unggulan</div>
                    <div class="sub"> Ministry of Education</div>
                    2019
                </div>
                <div class="content pads">
                    <div class="sub bigger">2nd Place Bridge Competition</div>
                    <div class="sub"> Piala Ketua Umum IKA Undip</div>
                    U-21 Team Category <br>
                    2019
                </div>
                <div class="content pads">
                    <div class="sub bigger">1st Place Bridge Competition</div>
                    <div class="sub"> PORPROV XII</div>
                    U-21 Team Category and U21 Pair Category<br>
                    2019
                </div>
                <div class="content pads">
                    <div class="sub bigger">1st Place Bridge Competition</div>
                    <div class="sub">Kejurprov Bridge Kalimantan Barat XVI</div>
                    U-20 Team Category<br>
                    2019
                </div>
            </div>
            </div>
        </div>
    </body>
    {% endblock %}
</html>

story4/templates/edu.html
{% extends 'base.html' %}
{% load static %}
<html>
    <head>
        <title>Education</title>
        {% block head %}
        <link rel="stylesheet" href="{%static 'css/bootstrap-grid' %}" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link href="{%static 'style.css' %}" rel="stylesheet" type="text/css" />
        {% endblock %}
    </head>
    {%block content %}
    <body style="background: #FFA300;;">
        <div class="row page ">
            <div>
                <a href="{% url 'story4:index' %}">
                <img class="buttonimg big" src="{%static 'button.png' %}">
                </a>
            </div>
            <div class="textbox pages">
                <div class="subtitle bigger">
                    Education
                </div>
                <div class="volun">
                <div class="content pads">
                    <div class="sub bigger">University of Indonesia</div>
                    <div class="sub">  Bachelor's degree, Computer Science</div>
                   2019-2022
                </div>
                <div class="content pads">
                    <div class="sub bigger">SMAN 1 Pontianak</div>
                    <div class="sub"> High School Diploma, Natural Sciences</div>
                    2016-2019
                </div>
                <div class="content pads">
                    <div class="sub bigger">SMPN 10 Pontianak</div>
                    <div class="sub"> Junor High School</div>
                    2016-2019
                </div>
                <div class="content pads">
                    <div class="sub bigger">SD Swasta Mujahidin</div>
                    <div class="sub"> Elementary School</div>
                    2016-2019
                </div>
            </div>
            </div>
        </div>
    </body>
    {% endblock %}
</html>

story4/templates/experience.html
{% extends 'base.html' %}
{% load static %}
<html>
    <head>
        <title>Experience</title>
        {% block head %}
        <link rel="stylesheet" href="{%static 'css/bootstrap-grid' %}" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link href="{%static 'style.css' %}" rel="stylesheet" type="text/css" />
        {% endblock %}
    </head>
    {%block content %}
    <body style="background: #FFA300;;">
        <div class="row page ">
            <div>
                <a href="{% url 'story4:index' %}">
                <img class="buttonimg big" src="{%static 'button.png' %}">
                </a>
            </div>
            <div class="textbox pages" style="">
                <div class="subtitle bigger">
                    Experience
                </div>
                <div class="content pad">
                    <div class="sub bigger">Teaching Assistant</div>
                    <div class="sub"> Universitas Indonesia, part-time</div>
                    2020-2021
                </div>
                <div class="content pad">
                    <div class="sub bigger">Product Division</div>
                    <div class="sub"> Akademis.id, internship</div>
                    2020-2021
                </div>
            </div>
        </div>
    </body>
    {% endblock %}
</html>

story4/templates/index.html
<!DOCTYPE html>
<html lang="en">
    {% extends 'base.html' %}
{% load static %}
<html>

    <head>
        <meta charset="utf-8">
        {% block head %}
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">    
        <title>Home</title>
        <link rel="stylesheet" href="{%static 'css/bootstrap-grid' %}" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous" type="text/css">
        <link rel="stylesheet" href="{%static 'css/bootstrap' %}" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous" type="text/css">
        <link href="{%static 'style.css' %}" rel="stylesheet" type="text/css" />
        {% endblock %}
    </head>
    
    <body>
        
        {%block content %}
        <div class="wrapper ">
            <div class="prof">
                <back>
                   <img class="idcard" src="{%static 'idcard.PNG' %}">
                </back>
                <div>
                    <img class=tengah src="{%static 'gilangcy.PNG' %}" >
                </div>
                <div class="context">
                    <div class="content" style="text-align: center;">
                        <div class="sub">Gilang Catur Yudishtira</div>
                       Computer Science Student at Universitas Indonesia
                    </div>
                    <div class="contact">
                        <div>
                           <img class="imgcp" src="{%static 'born.png' %}">
                        </div>
                        <div>
                            Pontianak, 20 November 2001
                        </div>
                        <div>
                            <img class="imgcp" src="{%static 'mail.png' %}">
                        </div>
                        <div>
                            gilangcaturyudistira@gmail.com
                        </div>
                        <div>
                            <img class="imgcp" src="{%static 'phone.png' %}">
                        </div>
                        <div>
                           089531045813
                        </div>
                        <div>
                            <img class="imgcp" src="{%static 'adress.png' %}">
                        </div>
                        <div>
                            Sungai Raya Dalam St. Kota Pontianak, Kalimantan Barat
                        </div>
                        
                    </div>
                    
                </div>
            </div>
            <div class="section">
                <a href="{% url 'story4:about' %}">
                <div class="section1">
                    <div class="long-row">
                        <div>
                            <img class="buttonimg" src="{%static 'button.png' %}">
                        </div>
                        <div class="textbox">
                            <div class="subtitle">
                                About me
                            </div>
                            <div class="about">
                                I’m  a Computer Science Student and like anything about social service. I have confidence in public speaking. I like working in teams and learning new things
                            </div>
                        </div>
                    </div>
                </div>
                </a>
                <a href="{% url 'story4:volun' %}">
                <div class="section2">
                    <div class="long-row">
                        <div>
                            <img class="buttonimg" src="{%static 'button.png' %}">
                        </div>
                        <div class="textbox">
                            <div class="subtitle">
                                Voluntary Experiences
                            </div>
                            <div class="content">
                                <div class="volun">
                                    <div class="sub">Vice Project Officer
                                        <div class="isisub">
                                            Bimbingan Belajar Gratis Fasilkom UI <br>
                                             2020-2021
                                        </div>
                                    </div>
                                    
                                    <div class="sub">Staff of Social Service Dept.
                                        <div class="isisub">
                                            BEM Fasilkom UI <br>
                                             2020-2021
                                        </div>
                                    </div>
                                    <div class="sub">Project Officer
                                        <div class="isisub">
                                            Yok Budak Masok UI 2021 <br>
                                             2020-2021
                                        </div>
                                    </div>
                                    <div class="sub">Staff of Sponsorship
                                        <div class="isisub">
                                            Pesta Rakyat Komputer <br>
                                             2020-2020
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                </a>
            </div>
            <div class="containers">
                <a href="{% url 'story4:edu' %}">
                <div class="row">
                    <div >
                        <img class="buttonimg" src="{%static 'button.png' %}">
                    </div>
                    <div class="textbox">
                        <div class="subtitle">
                            Education
                        </div>
                        <div class="content">
                            <div class="sub">University of Indonesia</div>
                           Bachelor's degree, Computer Science<br>
                           2019-2022
                        </div>
                        <div class="content">
                            <div class="sub">SMAN 1 Pontianak</div>
                           High School Diploma, Natural Sciences<br>
                           2016-2019
                        </div>
                    </div>
                </div>
                </a>
                <a href="{% url 'story4:experience' %}">
                <div class="row">
                    <div>
                        <img class="buttonimg" src="{%static 'button.png' %}">
                        
                    </div>
                    <div class="textbox">
                        <div class="subtitle">
                            Experiences
                        </div>
                        <div class="content">
                            <div class="sub">Teaching Assistant</div>
                           Universitas Indonesia, part time <br>
                           2020-2021
                        </div>
                        <div class="content">
                           <div class="sub">Product Division</div>
                           Akademis.id, internship <br>
                           2020-2021
                        </div>
                    </div>
                </div>
                </a>
            </div>
            <div class="containers">
                <a href="{% url 'story4:skills' %}">
                <div class="row">
                    <div>
                        <img class="buttonimg" src="{%static 'button.png' %}">
                    </div>
                    <div class="textbox">
                        <div class="subtitle">
                            Skills
                        </div>
                        <div class="content">
                            <div class="sub">
                            Python <br><br>
                            Java <br><br>
                            Fiction Writing <br><br>
                            Public Speaking
                            </div> 
                        </div>
                    </div>
                </div>
                </a>
                <a href="{% url 'story4:achievement' %}">
                <div class="row" >
                    <div>
                        <img class="buttonimg" src="{%static 'button.png' %}">
                    </div>
                    <div class="textbox">
                        <div class="subtitle">
                            Achievements
                        </div>
                        <div class="content">
                            <div class="sub">Awardee Beasiswa Unggulan</div>
                           Ministry of Education <br>
                           2019
                        </div>
                        <div class="content">
                            <div class="sub">2nd Place Bridge Competition</div>
                            Piala Ketua Umum IKA UNDIP<br>
                            U-21 Team Category <br>
                            2019
                        </div>
                    </div>
                </div>
                </a>
            </div>
        </div>
        {% endblock %}
    </body>
   
</html>

story4/templates/skills.html
{% extends 'base.html' %}
{% load static %}
<html>
    <head>
        <title>SKills</title>
        {% block head %}
        <link rel="stylesheet" href="{%static 'css/bootstrap-grid' %}" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link href="{%static 'style.css' %}" rel="stylesheet" type="text/css" />
        {% endblock %}
    </head>
    {%block content %}
    <body style="background: #FFA300;;">
        <div class="row page ">
            <div>
                <a href="{% url 'story4:index' %}">
                <img class="buttonimg big" src="{%static 'button.png' %}">
                </a>
            </div>
            <div class="textbox pages" style="padding-left: 2em;">
                <div class="subtitle bigger" style="padding-left: 0em;">
                    Skills
                </div>
                <div class="volun">
                    <div class="sub bigger padss ">Python</div>
                    <div class="sub bigger padss ">Java</div>
                    <div class="sub bigger padss ">Fiction Writing</div>
                    <div class="sub bigger padss ">Public Speaking</div>
                </div>
            </div>
        </div>
    </body>
    {% endblock %}
</html>

story4/templates/volun.html
{% extends 'base.html' %}
{% load static %}
<html>
    <head>
        <title>Voluntary</title>
        {% block head %}
        <link rel="stylesheet" href="{%static 'css/bootstrap-grid' %}" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link href="{%static 'style.css' %}" rel="stylesheet" type="text/css" />
        {% endblock %}
    </head>
    {%block content %}
    <body style="background: #FFA300;;">
        <div class="row page ">
            <div>
                <a href="{% url 'story4:index' %}">
                <img class="buttonimg big" src="{%static 'button.png' %}">
                </a>
            </div>
            <div class="textbox pages" style="min-height: 1200px;">
                <div class="subtitle bigger">
                    Voluntary Experiences
                </div>
                <div class="volun">
                <div class="sub pads">
                    <div class="sub bigger">Vice Project Officer</div>
                    <div class="sub"> Bimbingan Belajar Gratis Fasilkom UI</div>
                    2020-21
                </div>
                <div class="sub pads">
                    <div class="sub bigger">Project Officer</div>
                    <div class="sub"> Yok Budak Masok UI 2021</div>
                    2020-2021
                </div>
                <div class="sub pads">
                    <div class="sub bigger">Staff Of Social Service Dept.</div>
                    <div class="sub"> BEM Fasilkom UI</div>
                    2020-2021
                </div>
                <div class="sub pads">
                    <div class="sub bigger">Staff of Sponsorship</div>
                    <div class="sub"> Pesta Rakyat Komputer</div>
                    2020-2021
                </div>
                <div class="sub pads">
                    <div class="sub bigger">Staff of Ticketing</div>
                    <div class="sub"> Yok Budak Masok UI 2020</div>
                    2019-2020
                </div>
                <div class="sub pads">
                    <div class="sub bigger">Teacher</div>
                    <div class="sub">Rumah Belajar BEM UI</div>
                    2020-2020
                </div>
                <div class="sub pads">
                    <div class="sub bigger">Vice Head of Mentor and Participants</div>
                    <div class="sub"> Bimbingan Belajar Gratis Fasilkom UI</div>
                    2019-2020
                </div>
                </div>
            </div>
        </div>
    </body>
    {% endblock %}
</html>