story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story4.urls')),
    path('', include('story1.urls')),
    path('',include('story5.urls')),
    path('',include('story6.urls')),
    path('',include('story7.urls')),
    path('',include('story8.urls')),
     path('',include('story9.urls'))
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns = [
    path('',views.loginstory9,name = 'story9'),
    path('story9/',views.loginstory9,name = 'story9'),
    path('halaman/',views.story9,name='halaman'),
    path('logout/',views.logoutstory,name='logoutstory'),
    path('register/',views.register,name='register')
]

story9/models.py
from django.db import models

# Create your models here.

story9/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class formUsers(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username','password')
        labels = {'username':'Username :','password':'Password :'}
        


class formUser(UserCreationForm):
    password1 = forms.CharField(label='Enter password :', 
                                widget=forms.PasswordInput(attrs={'class':'form-control','placeholder': "Put your password here",  "autocomplete":"off"}))
    password2 = forms.CharField(label='Confirm password :', 
                                widget=forms.PasswordInput(attrs={'class':'form-control','placeholder': "Confirm your password here",  "autocomplete":"off"}))
    class Meta:
        model=User
        fields=("username","first_name",
                "last_name","password1","password2",)
        labels ={'username':'Username :',"first_name":'First Name :',
                "last_name":'Last Name :',}
        help_texts = {
            "username":None,
        }
        widgets ={
            'username': forms.TextInput(attrs={'class':'form-control','placeholder': "Put your username here",  "autocomplete":"off"}),
            'first_name': forms.TextInput(attrs={'class':'form-control','placeholder': "Put your First name here",  "autocomplete":"off"}),
            'last_name': forms.TextInput(attrs={'class':'form-control','placeholder': "Put your Last name here",  "autocomplete":"off"}),
            }
        
        
    
        
        

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, User
from django.contrib.auth import authenticate, login ,logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import formUser

# Create your views here.
def story9(request):
    if User.is_authenticated:
        return render(request,'halaman.html')
    else :
        return redirect('story9:story9')

def logoutstory(request):
    return redirect('story9:story9')

def loginstory9(request):
    logout(request)
    context = {
		'page_title':'LOGIN',
	}
    user = None
    if request.method == "POST":
        username_login = request.POST['username']
        password_login = request.POST['password']
        user = authenticate(request, username=username_login, password=password_login)
        if user is not None:
            login(request,user)
            return redirect('story9:halaman')
           
        else:
            messages.warning(request, f'Username atau Password anda salah!')
            return redirect('story9:story9')
           
		
    return render(request, 'story9.html', context)

def register(request):
    form = formUser(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(request, f'Akun anda berhasil dibuat')
            return redirect('story9:story9')
    return render(request,'register.html',{'form_user':form})

 

story9/templates/halaman.html
<html>
    {% load static %}
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'story9.css' %}">
    <title>Story</title>
</head>

<body>
  <center>
    <div class="container">
          <div class="card login-card">
            <h1>Selamat Datang</h1> <h3> <b>{{user.first_name}} {{user.last_name}}</b> </h3><br>
            <a class="btn btn-danger" href="{% url 'story9:logoutstory' %}">Logout</a>
              </div>
            
      </div>
  </center>
</body>
</html>

story9/templates/register.html
<html>
    {% load static %}
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'story9.css' %}">
    <title>Story</title>
</head>

<body>
  <center>
    <div class="container">
          <div class="card login-card">
            <form method="POST">
                {% csrf_token %}
                    {{form_user.as_p}}
            <small>Harap gunakan Password dengan minimal 8 huruf dengan kombinasi huruf kapital dan angka</small><br>
            <a href="{{request.META.HTTP_REFERER}}" class="btn btn-danger">Back</a><button type="Submit" class="btn btn-login">Sign Up</button>
            </form>
      </div>
  </center>
</body>
</html>

story9/templates/story9.html
<html>
    {% load static %}
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'story9.css' %}">
    <title>Story</title>
</head>

<body>
  <center>
    <div class="container">
          <div class="card login-card">
            <form method="POST">
              {%csrf_token%}
                <div class="form-group"> 
                    <label for="exampleInputEmail1">Username</label>
                    <input name="username" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Username" >
                  </div>
                  <div class="form-group">
                    <label for="exampleInputPassword1">Password</label>
                    <input name="password" type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                  </div>
                  <a href="{% url 'story9:register'%}"  class="btn btn-login" >Sign Up</a><button type="submit" class="btn btn-login">Sign In</button><br>
                  {% if messages %}
                  {% for message in messages %}
                    <p>{{message}}</p>
                    
                  {% endfor %}
                  {% endif %}
                  </form>
                 
              </div>
      </div>
  </center>
</body>
</html>